/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Marcos Perez
 */
public class DatosEst extends javax.swing.JDialog {
    
    private ArrayList<String> postOrden;
    private ArrayList<String> preOrden;
    private ArrayList<String> inOrden;
    private int[] datos = new int[6]; //0-nivel 1-altura 2-cantNodoPadre 3-cantNodoHijo 4-nivelDer 5-nivelIzq
    DefaultListModel modPreOrden;
    DefaultListModel modInOrden;
    DefaultListModel modPostOrden;
    /**
     * 
     * @param postOrden
     * @param preOrden
     * @param inOrden
     * @param nivel datos[0]
     * @param cantNodos datos[1]
     * @param cantNodoPadre datos[2]
     * @param cantNodoHIjo datos[3]
     * @param nivelDer datos[4]
     * @param nivelIzq datos[5]
     */
    public void setDatosEst(ArrayList<String> postOrden, ArrayList<String> preOrden, ArrayList<String> inOrden, String nivel, int cantNodos, int cantNodoPadre, int cantNodoHIjo, String nivelDer, String nivelIzq) {
        this.postOrden = postOrden;
        this.preOrden = preOrden;
        this.inOrden = inOrden;
        this.jlblNivel.setText(nivel);
        this.jlblNodos.setText(String.valueOf(cantNodos));
        this.jlblNodosR.setText(String.valueOf(cantNodoPadre));
        this.jlblNodosH.setText(String.valueOf(cantNodoHIjo));
        this.jlblNivelDer.setText(nivelDer);
        this.jlblNivelIzq.setText(nivelIzq);
        modInOrden = new DefaultListModel();
        modPostOrden = new DefaultListModel();
        modPreOrden = new DefaultListModel();
        for(int i=0; i<postOrden.size(); i++){
            modPostOrden.addElement(postOrden.get(i));
        }
        for(int i=0; i<preOrden.size(); i++){
            modPreOrden.addElement(preOrden.get(i));
        }
         for(int i=0; i<postOrden.size(); i++){
            modInOrden.addElement(inOrden.get(i));
        }
        jlistIn.setModel(modInOrden);
        jlistPost.setModel(modPostOrden);
        jlistPre.setModel(modPreOrden);
    }
   
    public DatosEst(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblAtras = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlblNodosR = new javax.swing.JLabel();
        jlblNodos = new javax.swing.JLabel();
        jlblNivel = new javax.swing.JLabel();
        jlblNodosH = new javax.swing.JLabel();
        jlblNivelDer = new javax.swing.JLabel();
        jlblNivelIzq = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistPre = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistIn = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlistPost = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(66, 133, 244)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblAtras.setBackground(new java.awt.Color(66, 133, 244));
        jlblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblAtrasMouseClicked(evt);
            }
        });
        jlblAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jlblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 802, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblNodosR.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlblNodosR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNodosR.setText("0");
        jPanel3.add(jlblNodosR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 100, 65));

        jlblNodos.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlblNodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNodos.setText("0");
        jPanel3.add(jlblNodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 100, 65));

        jlblNivel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlblNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNivel.setText("0");
        jPanel3.add(jlblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, 65));

        jlblNodosH.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlblNodosH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNodosH.setText("0");
        jPanel3.add(jlblNodosH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 65));

        jlblNivelDer.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlblNivelDer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNivelDer.setText("0");
        jPanel3.add(jlblNivelDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 100, 65));

        jlblNivelIzq.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlblNivelIzq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNivelIzq.setText("0");
        jPanel3.add(jlblNivelIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 100, 65));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nodos Hojas");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nodos Raiz");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 120, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nodos");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 120, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Altura del Arbol");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 130, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Altura Arbol Izquierdo");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 130, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Altura Arbol Derecho");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 130, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 500, 290));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DATOS ESTADISTICOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 210, 30));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlistPre.setBackground(new java.awt.Color(204, 204, 204));
        jlistPre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlistPre.setForeground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(jlistPre);

        jTabbedPane1.addTab("PreOrden", jScrollPane1);

        jlistIn.setBackground(new java.awt.Color(204, 204, 204));
        jlistIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlistIn.setForeground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setViewportView(jlistIn);

        jTabbedPane1.addTab("InOrden", jScrollPane2);

        jlistPost.setBackground(new java.awt.Color(204, 204, 204));
        jlistPost.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlistPost.setForeground(new java.awt.Color(153, 153, 153));
        jScrollPane3.setViewportView(jlistPost);

        jTabbedPane1.addTab("postOrden", jScrollPane3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblAtrasMouseClicked

    }//GEN-LAST:event_jlblAtrasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jlblAtras;
    private javax.swing.JLabel jlblNivel;
    private javax.swing.JLabel jlblNivelDer;
    private javax.swing.JLabel jlblNivelIzq;
    private javax.swing.JLabel jlblNodos;
    private javax.swing.JLabel jlblNodosH;
    private javax.swing.JLabel jlblNodosR;
    private javax.swing.JList<String> jlistIn;
    private javax.swing.JList<String> jlistPost;
    private javax.swing.JList<String> jlistPre;
    // End of variables declaration//GEN-END:variables
}
