/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import net.sf.jcarrierpigeon.Notification;
import net.sf.jcarrierpigeon.NotificationQueue;
import net.sf.jcarrierpigeon.WindowPosition;

/**
 *
 * @author Conectall Project
 */
public class Notificacion extends javax.swing.JFrame {

    /**
     * Creates new form Notification
     */
    public Notificacion(String nombre, boolean c) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        
        if(c){
            
            this.jblTitulo.setText("!Enhorabuena¡");
            this.jlbSubtitulo.setText("!Ahora tienes un nuevo amigo¡");
            this.jlbName.setText("Haz agregado a: "+nombre);
            
        }else{
            this.jblTitulo.setText("!Ups¡");
            this.jlbSubtitulo.setText("!A poco piensas quedarte sin amigos¡");
            this.jlbName.setText("Haz elimado a: "+nombre);
            
        }
       
        
        Notification alerta = new Notification(this, WindowPosition.BOTTOMRIGHT, 0, 0, 5000);
        NotificationQueue alertas = new NotificationQueue();
        alertas.add(alerta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNotification = new javax.swing.JPanel();
        jlbSubtitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jblTitulo = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelNotification.setBackground(new java.awt.Color(204, 204, 204));

        jlbSubtitulo.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jlbSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSubtitulo.setText("¡Ahora tienes un nuevo amigo!");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblTitulo.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTitulo.setText("¡Enhorabuena!");
        jPanel1.add(jblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 20));

        jlbName.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jlbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbName.setText("Mira de que se trata!");

        javax.swing.GroupLayout PanelNotificationLayout = new javax.swing.GroupLayout(PanelNotification);
        PanelNotification.setLayout(PanelNotificationLayout);
        PanelNotificationLayout.setHorizontalGroup(
            PanelNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
            .addComponent(jlbSubtitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNotificationLayout.createSequentialGroup()
                .addComponent(jlbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelNotificationLayout.setVerticalGroup(
            PanelNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNotificationLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(PanelNotification, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNotification;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbSubtitulo;
    // End of variables declaration//GEN-END:variables
}
